sudo: required

services:
  - docker
  
services:
  - docker

script:
  - docker run --rm -e SONAR_HOST_URL="https://sonar.zdrive.ir/" -e SONAR_LOGIN="${SONAR_TOKEN}" -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli

# cache:
#   directories:
#     - /home/travis/.sonarcache

# script:
#   - mkdir -p /home/travis/.sonarcache
#   - docker run --rm \
#         -u "$(id -u):$(id -g)" \
#         -e SONAR_HOST_URL="https://sonar.zdrive.ir" \
#         -v "$(pwd):/usr/src" \
#         -v "/home/travis/.sonarcache:/opt/sonar-scanner/.sonar/cache" \
#         lequal/sonar-scanner


# sudo: required

# addons:
#   sonarcloud:
#     organization: "masoud91"
#     token: ${SONAR_TOKEN}

#   sonarqube: true



#     - sonar-scanner -D sonar.host.url=https://sonar.zdrive.ir/ -D sonar.login=${SONAR_TOKEN} -X
#   - sonar-scanner
#   - docker build -f Dockerfile-py3 -t masoud92_swift:latest .

# sonar_cloud_token = 80dc43d7cb3571803dbbbefa67852ada7faff57c

# language: python

# matrix:
#   include:
#    - env: TOXENV=py37
#      python: 3.7
#    - env: TOXENV=py27
#      python: 2.7
#    - env: TOXENV=pep8
#      python: 3.7

# install: 
#   - sudo apt-get update
#   - sudo apt-get install curl gcc memcached rsync sqlite3 xfsprogs git-core libffi-dev python-setuptools liberasurecode-dev libssl-dev
#   - sudo apt-get install python-coverage python-dev python-nose python-xattr python-eventlet python-greenlet python-pastedeploy python-netifaces python-pip python-dnspython python-mock
#   - pip install tox

# script: tox

# language: python

# python:
#   - "3.7"

# services:
#   - docker
  
# script:
#   - docker build -f Dockerfile-py3 -t swift_service .
#   - docker run --rm swift_service sh -c "tox


# matrix:
#   include:
#    - env: TOXENV=py37
#      python: 3.7
#    - env: TOXENV=py27
#      python: 2.7
#    - env: TOXENV=pep8
#      python: 3.7

# install: 
#     - pip install tox
#     - sudo apt-get install liberasurecode-dev
#     - sudo apt-get install ssh rsync

# script: tox

# language: python
# python: 3.7

# matrix:
#   include:
#    - env: TOXENV=py37
#      python: 3.7
#    - env: TOXENV=py27
#      python: 2.7
#    - env: TOXENV=pep8
#      python: 3.7

# script: 
#   - apt-get install liberasurecode-dev
#   - apt-get install ssh rsync
#   - tox
