language: python

before_script: apt-get install liberasurecode-dev

matrix:
  include:
   - env: TOXENV=py37
     python: 3.7
   - env: TOXENV=py27
     python: 2.7
   - env: TOXENV=pep8
     python: 3.7

script: tox
